#!/bin/bash
# This script generates source code for each stage (aka version) of `site`
# using AMLEO: https://bitbucket.org/ogstudio/amleo

DIR=`dirname $0`
STG=$DIR/stages
GEN=amleo.py

# 01.Empty.
$GEN $STG/01*/{Variants.txt,templates} $STG/01*/variants
# 02.Excerpts.
$GEN $STG/02*/{Variants.txt,templates} $STG/0{1,2}*/variants
# 03.ExcerptStyle.
$GEN $STG/03*/{Variants.txt,templates} $STG/0{1,2,3}*/variants
# 04.News.
$GEN $STG/04*/{Variants.txt,templates} $STG/0{1,2,3,4}*/variants
# 05.NewsTemplates.
$GEN $STG/05*/{Variants.txt,templates} $STG/0{1,2,3,4,5}*/variants
# 06.Pagination.
$GEN $STG/06*/{Variants.txt,templates} $STG/0{1,2,3,4,5,6}*/variants
# 07.Language.
$GEN $STG/07*/{Variants.txt,templates} $STG/0{1,2,3,4,5,6,7}*/variants
