#!/bin/bash

STAGE=$1

if [ -z "$STAGE" ];
then
    echo "Usage: $0 STAGE"
    exit 1
fi

DIR=`dirname $0`

STG=$DIR/stages/$STAGE

cp $STG/index.html $DIR
cp $STG/games.html $DIR
cp $STG/generate-news.py $DIR
